- name: make crc
  shell:
    executable: /bin/bash
    cmd: |
      export PATH=$PATH:$HOME/bin
      export PULL_SECRET=~/upstream/git/openstack-k8s-operators/pull-secret.txt
      export CPUS=10
      # 16G is not enough if meta, nova, neutron is deployed
      export MEMORY=20480
      cd ~/upstream/git/openstack-k8s-operators/install_yamls/devsetup
      make crc || true
  tags:
    - crc

- name: create env.sh
  shell:
    cmd: |
      rm -rf ~/crc-env.source
      echo 'export PATH=$PATH:$HOME/bin' >> ~/crc-env.source
      echo 'eval $(crc oc-env)' >> ~/crc-env.source
      echo 'oc login --username kubeadmin -p 12345678' >> ~/crc-env.source
      echo 'export OS_CLOUD=local-crc' >> ~/crc-env.source
  tags:
    - crc


